services:

  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "./data:/app/data"
    restart: unless-stopped

  db:
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_USER: imec_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: imec_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data

  db15:
    image: postgres:15
    container_name: db15_temp
    environment:
      POSTGRES_USER: imec_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: imec_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_dump:/dump



volumes:
  pgdata: